name: Create and Release NuGet Package
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: Continuous Integration
    container: mcr.microsoft.com/dotnet/sdk:5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Packge NuGet Project
        run: dotnet pack -p:PackageVersion=1.1.2 --output out
      - name: Store NuGet Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: Preview.CSharp.Templates.1.1.2.nupkg
  cd:
    name: Continous Deployment
    container: mcr.microsoft.com/dotnet/sdk:5
    steps:
      - name: Download Artifact Containing NuGet Package
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: Push to NuGet
        run: dotnet nuget push Preview.CSharp.Templates.1.1.2.nupkg --source https://api.nuget.org/v3/index.json --api-key